import Foundation

/// Lightweight i18n for GuardClaw Bar.
/// Access via `Loc.shared.t("key")` — SwiftUI views will auto-update when language changes
/// because `Loc` is @Observable and `t()` reads the tracked `lang` property.
@Observable
final class Loc: @unchecked Sendable {
    static let shared = Loc()

    var lang: String {
        didSet { SettingsStore.shared.language = lang }
    }

    private init() {
        lang = SettingsStore.shared.language
    }

    func toggle() {
        lang = lang == "en" ? "zh" : "en"
    }

    /// Look up a localized string. Falls back to English, then returns the key itself.
    func t(_ key: String) -> String {
        let dict = lang == "zh" ? Self.zh : Self.en
        return dict[key] ?? Self.en[key] ?? key
    }

    /// Look up with simple string interpolation: `{{0}}`, `{{1}}`, etc.
    func t(_ key: String, _ args: Any...) -> String {
        var s = t(key)
        for (i, arg) in args.enumerated() {
            s = s.replacingOccurrences(of: "{{\(i)}}", with: "\(arg)")
        }
        return s
    }

    // MARK: - English Strings

    static let en: [String: String] = [
        // Common
        "common.install": "Install",
        "common.uninstall": "Uninstall",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.apply": "Apply",
        "common.add": "Add",
        "common.loading": "Loading...",
        "common.connected": "Connected",
        "common.disconnected": "Disconnected",
        "common.notConnected": "Not connected",
        "common.approve": "Approve",
        "common.deny": "Deny",
        "common.review": "Review",
        "common.stop": "Stop",
        "common.run": "Run",
        "common.back": "Back",
        "common.skip": "Skip",
        "common.next": "Next",
        "common.getStarted": "Get Started",
        "common.download": "Download",
        "common.detect": "Detect",
        "common.clean": "Clean",
        "common.active": "Active",
        "common.blocked": "BLOCKED",
        "common.flagged": "FLAGGED",

        // MenuPopoverView
        "header.title": "GuardClaw",
        "header.daysSuffix": "d",
        "header.saved": "saved",

        // FooterView
        "footer.openDashboard": "Open Dashboard",
        "footer.checkUpdates": "Check for updates",
        "footer.available": "{{0}} available",

        // SettingsView (popover)
        "settings.title": "Settings",
        "settings.judge": "Judge",
        "settings.builtIn": "Built-in",
        "settings.lmStudio": "LM Studio",
        "settings.ollama": "Ollama",
        "settings.connections": "Connections",
        "settings.protection": "Protection",
        "settings.activeBlocking": "Active Blocking",
        "settings.blockingOn": "Risky tool calls require approval",
        "settings.blockingOff": "Monitor only — nothing blocked",
        "settings.failClosed": "Fail-Closed (Offline)",
        "settings.failClosedOn": "When GuardClaw or the judge is unreachable, risky tool calls are blocked instead of slipping through unreviewed.",
        "settings.failClosedOff": "Risk: if the judge times out, crashes, or is offline, risky tool calls can continue without GuardClaw approval.",
        "settings.gatewayToken": "Gateway Token",
        "settings.tokenPlaceholder": "Token",
        "settings.tokenSaved": "Token saved",
        "settings.autoDetected": "Auto-detected from OpenClaw config",
        "settings.noTokenFound": "No token found in OpenClaw config",
        "settings.notFound": "Not found",
        "settings.serverURL": "Server URL",
        "settings.pollInterval": "Poll Interval: {{0}}s",
        "settings.hooksInstalled": "Hooks installed — restart {{0}}",
        "settings.hooksRemoved": "Hooks removed — restart {{0}}",
        "settings.pluginInstalled": "Plugin installed — restart {{0}}",
        "settings.pluginRemoved": "Plugin removed — restart {{0}}",
        "settings.failed": "Failed: {{0}}",
        "settings.rec": "rec",
        "settings.setupRun": "Setup & Run",
        "settings.downloading": "Downloading... {{0}}%",
        "settings.loadingModel": "Loading model...",
        "settings.language": "Language",

        // SidebarView
        "sidebar.monitor": "MONITOR",
        "sidebar.security": "SECURITY",
        "sidebar.tools": "TOOLS",
        "sidebar.settings": "SETTINGS",
        "sidebar.dashboard": "Dashboard",
        "sidebar.activity": "Activity",
        "sidebar.approvals": "Approvals",
        "sidebar.rules": "Rules",
        "sidebar.memory": "Memory",
        "sidebar.securityScan": "Security Scan",
        "sidebar.benchmark": "Benchmark",
        "sidebar.judge": "Judge",
        "sidebar.connections": "Connections",
        "sidebar.protection": "Protection",

        // DashboardView
        "dashboard.title": "Dashboard",
        "dashboard.daysProtected": "Days Protected",
        "dashboard.totalEvents": "Total Events",
        "dashboard.pending": "Pending",
        "dashboard.safeEvents": "Safe Events",
        "dashboard.warnings": "Warnings",
        "dashboard.blocked": "Blocked",
        "dashboard.securityScan": "Security Scan",
        "dashboard.risky": "{{0}} risky",
        "dashboard.connections": "Connections",
        "dashboard.judgeLabel": "Judge ({{0}})",
        "dashboard.ready": "Ready",
        "dashboard.tokenUsage": "Token Usage",
        "dashboard.today": "Today",
        "dashboard.cumulative": "Cumulative",
        "dashboard.noTokenData": "No token data yet",
        "dashboard.recentHighRisk": "Recent High-Risk Events",
        "dashboard.inTokens": "In: {{0}}",
        "dashboard.outTokens": "Out: {{0}}",
        "dashboard.cacheTokens": "Cache: {{0}}",
        "dashboard.requests": "{{0}} requests",
        "dashboard.tokens": "{{0}} tokens",

        // ActivityView
        "activity.title": "Activity",
        "activity.backend": "Backend",
        "activity.noActivity": "No Activity Yet",
        "activity.noActivityDesc": "Events will appear here as tool calls are intercepted",
        "activity.markAllow": "Mark Allow",
        "activity.markDeny": "Mark Deny",

        // ApprovalsPageView
        "approvals.title": "Approvals",
        "approvals.noApprovals": "No Pending Approvals",
        "approvals.noApprovalsDesc": "High-risk tool calls will appear here for review",
        "approvals.pending": "{{0}} pending",
        "approvals.riskScore": "Risk Score",
        "approvals.alwaysApprove": "Always Approve",
        "approvals.waiting": "Waiting {{0}}s",
        "approvals.unknownTool": "Unknown tool",
        "approvals.risk": "Risk: {{0}}/10",

        // ProviderCardView
        "card.connection": "CONNECTION",
        "card.stats": "STATS",
        "card.events": "Events: {{0}}",
        "card.safe": "Safe",
        "card.warn": "Warn",
        "card.block": "Block",
        "card.judgeTokens": "Judge: {{0}} tokens · {{1}} calls",
        "card.pendingApprovals": "PENDING APPROVALS ({{0}})",
        "card.recentFlagged": "RECENT FLAGGED / BLOCKED",
        "card.securityScan": "SECURITY SCAN",
        "card.scanning": "Scanning...",
        "card.todayTokens": "Today: {{0}} ({{1}} req)",
        "card.totalTokens": "Total: {{0}} ({{1}} req)",
        "card.tools": "Tools",
        "card.skills": "Skills",
        "card.vulns": "{{0}} Vulns",
        "card.riskyCount": "({{0}} risky)",

        // Detail rows
        "detail.time": "Time",
        "detail.score": "Score",
        "detail.category": "Category",
        "detail.reason": "Reason:",
        "detail.judgeBackend": "Judge",

        // RulesView
        "rules.title": "Rules",
        "rules.suggestedRules": "Suggested Rules",
        "rules.basedOnHistory": "Based on your approve/deny history",
        "rules.aiSuggest": "AI Suggest",
        "rules.allow": "Allow",
        "rules.block": "Block",
        "rules.whitelist": "Whitelist",
        "rules.whitelistDesc": "Always auto-allowed without scoring",
        "rules.blacklist": "Blacklist",
        "rules.blacklistDesc": "Always auto-blocked",
        "rules.addedTo": "Added {{0}} to {{1}}",
        "rules.noPatterns": "No patterns yet",
        "rules.quickPresets": "Quick Presets",
        "rules.presetApplied": "Preset applied",
        "rules.addedWhitelist": "Added to whitelist",
        "rules.addedBlacklist": "Added to blacklist",
        "rules.patternPlaceholder": "Tool name or pattern...",
        "rules.howPatternsWork": "How Patterns Work",
        "rules.patternsHelp": "Patterns match tool names (e.g. \"Bash\") or tool:command pairs (e.g. \"Bash:git status\"). Whitelist overrides all scoring; blacklist blocks immediately.",
        "rules.allowFileReads": "Allow all file reads",
        "rules.allowSearches": "Allow Grep/Glob searches",
        "rules.allowGit": "Allow git status/log/diff",
        "rules.blockRmRf": "Block rm -rf",
        "rules.blockCurlWget": "Block curl/wget uploads",
        "rules.blockSSH": "Block SSH key access",
        "rules.blockEnv": "Block .env file reads",
        "rules.noAISuggestions": "No AI suggestions — make sure a judge model is loaded",
        "rules.aiSuggestionFailed": "AI suggestion failed: {{0}}",

        // MemoryView
        "memory.title": "Memory",
        "memory.totalDecisions": "Total Decisions",
        "memory.learnedPatterns": "Learned Patterns",
        "memory.autoApprove": "Auto-Approve",
        "memory.confidence": "Confidence",
        "memory.toolName": "Tool Name",
        "memory.sort": "Sort",
        "memory.noPatterns": "No Patterns Yet",
        "memory.noPatternsDesc": "GuardClaw learns from your approve/deny decisions",
        "memory.resetAll": "Reset All Memory",
        "memory.resetConfirm": "Reset all learned patterns?",
        "memory.resetWarning": "This cannot be undone. All approve/deny patterns will be cleared.",
        "memory.resetButton": "Reset Memory",
        "memory.cleared": "Memory cleared",
        "memory.confidencePercent": "{{0}}% confidence",

        // AuditView
        "audit.title": "Security Scan",
        "audit.headline": "Security Audit",
        "audit.description": "Static analysis powered by agent-audit. Scans MCP configs, credentials, code vulnerabilities, and OWASP Agentic Top 10.",
        "audit.runScan": "Run Scan",
        "audit.scanning": "Scanning...",
        "audit.configChanged": "Configuration changed since last scan",
        "audit.configChangedDesc": "MCP plugins or settings have been modified. Re-scan recommended.",
        "audit.rescan": "Re-scan",
        "audit.noIssues": "No Issues Found",
        "audit.noIssuesDesc": "Your configuration looks clean",
        "audit.notScanned": "Not Scanned Yet",
        "audit.notScannedDesc": "Click Run Scan to analyze your agent configuration",
        "audit.findings": "Findings",
        "audit.tools": "Tools",
        "audit.skills": "Skills",
        "audit.riskyTools": "Risky Tools",
        "audit.riskySkills": "Risky Skills",
        "audit.vulnerabilities": "Vulnerabilities",
        "audit.riskyNames": "Risky: {{0}}",
        "audit.vulnsFound": "{{0}} — {{1}} vulnerabilities found",
        "audit.blockExtension": "Block Extension",
        "audit.scanFailed": "Scan failed: {{0}}",

        // BenchmarkView
        "benchmark.title": "Benchmark",
        "benchmark.headline": "Accuracy Benchmark",
        "benchmark.description": "Tests the safety judge against 30 curated scenarios. Higher is better — aim for 85%+.",
        "benchmark.backend": "Backend",
        "benchmark.currentJudge": "Current Judge",
        "benchmark.model": "Model",
        "benchmark.auto": "Auto",
        "benchmark.abort": "Abort",
        "benchmark.runBenchmark": "Run Benchmark",
        "benchmark.latest": "Latest:",
        "benchmark.running": "Running...",
        "benchmark.noResults": "No Results Yet",
        "benchmark.noResultsDesc": "Run the benchmark to test your judge's accuracy",
        "benchmark.resultsHistory": "Results History",
        "benchmark.unknownModel": "Unknown model",
        "benchmark.done": "Done — accuracy: {{0}}%",
        "benchmark.aborted": "Aborted",
        "benchmark.error": "Error: {{0}}",
        "benchmark.correct": "{{0}}/{{1}} correct{{2}}",
        "benchmark.avgLatency": "Avg {{0}}ms",
        "benchmark.benchmarkAborted": "Benchmark aborted",

        // JudgeSettingsView
        "judge.title": "Judge",
        "judge.online": "Judge Online",
        "judge.offline": "Judge Offline",
        "judge.backend": "Backend",
        "judge.model": "Model",
        "judge.none": "None",
        "judge.switchBackend": "Switch Backend",
        "judge.builtInMLX": "Built-in (MLX)",
        "judge.anthropicClaude": "Anthropic Claude",
        "judge.builtInModels": "Built-in Models",
        "judge.noModels": "No built-in models available",
        "judge.lmStudioAt": "LM Studio at http://localhost:1234",
        "judge.ollamaAt": "Ollama at http://localhost:11434",
        "judge.anthropicKey": "Uses ANTHROPIC_API_KEY from environment",
        "judge.fetchingModels": "Fetching models...",
        "judge.availableModels": "Available Models",
        "judge.fetchModels": "Fetch Models",
        "judge.testConnection": "Test Connection",
        "judge.testConnected": "Connected",
        "judge.testFailed": "Connection failed",
        "judge.recommended": "RECOMMENDED",

        // ConnectionsView
        "connections.title": "Connections",
        "connections.hooksInstalled": "Hooks installed",
        "connections.ccDesc": "GuardClaw intercepts Claude Code tool calls via hooks installed in ~/.claude/settings.json.",
        "connections.hooksActive": "Hooks are active.",
        "connections.installHooks": "Install Hooks",
        "connections.ocGateway": "OpenClaw Gateway",
        "connections.pluginInstalled": "Interceptor plugin installed.",
        "connections.ocNeedPlugin": "The GuardClaw interceptor plugin needs to be installed in OpenClaw to enable tool call blocking.",
        "connections.installPlugin": "Install Plugin",
        "connections.tokenDesc": "Gateway token for real-time event streaming.",
        "connections.tokenPlaceholder": "Gateway token...",
        "connections.tokenSaved": "Token saved, reconnecting...",
        "connections.geminiDesc": "GuardClaw intercepts Gemini CLI tool calls via hooks installed in ~/.gemini/settings.json.",
        "connections.cursorDesc": "GuardClaw intercepts Cursor tool calls via hooks installed in ~/.cursor/hooks.json.",
        "connections.opencodeDesc": "GuardClaw intercepts OpenCode tool calls via a plugin installed in ~/.config/opencode/plugins/.",
        "connections.pluginActive": "Plugin is active.",
        "connections.hooksInstalledRestart": "Hooks installed — restart {{0}} to activate",
        "connections.pluginInstalledRestart": "Plugin installed — restart {{0}} to activate",
        "connections.hooksRemovedRestart": "Hooks removed — restart {{0}}",
        "connections.pluginRemovedRestart": "Plugin removed — restart {{0}}",
        "connections.noTokenFound": "No token found",
        "connections.autoDetected": "Auto-detected from OpenClaw config",

        // ProtectionView
        "protection.title": "Protection",
        "protection.activeBlocking": "Active Blocking",
        "protection.blockingOnDesc": "Risky tool calls require approval before executing.",
        "protection.blockingOffDesc": "Monitor only — GuardClaw watches but doesn't block anything.",
        "protection.failClosedOffline": "Fail-Closed (Offline)",
        "protection.failClosedOnDesc": "If the judge is unreachable, risky tool calls are blocked until protection recovers.",
        "protection.failClosedOffDesc": "If the judge is unreachable, risky tool calls may proceed without GuardClaw review.",
        "protection.offlineJudgeBehavior": "Offline Judge Behavior",
        "protection.failOpenRemoved": "Fail-open risk removed",
        "protection.failOpenActive": "Fail-open risk active",
        "protection.failClosedDetail": "If GuardClaw or the local judge times out, crashes, or is offline, risky actions stop and wait for recovery instead of running without review.",
        "protection.failOpenDetail": "If GuardClaw or the local judge times out, crashes, or is offline, risky actions may continue without review. This favors availability over safety.",
        "protection.strict": "Strict",
        "protection.strictDesc": "Active Blocking + Fail-Closed. Maximum protection.",
        "protection.balanced": "Balanced",
        "protection.balancedDesc": "Active Blocking + Fail-Open. Protection with availability fallback.",
        "protection.monitorOnly": "Monitor Only",
        "protection.monitorOnlyDesc": "No blocking. GuardClaw logs and alerts without intervening.",
        "protection.presets": "Presets",
        "protection.blockingEnabled": "Blocking enabled",
        "protection.blockingDisabled": "Blocking disabled",
        "protection.failClosedEnabled": "Fail-closed enabled — risky calls stop if GuardClaw goes offline",
        "protection.failClosedDisabled": "Fail-closed disabled — risky calls may continue if GuardClaw or the judge fails",

        // BarAuditSection
        "barAudit.securityAudit": "Security Audit",
        "barAudit.crit": "{{0}} CRIT",
        "barAudit.high": "{{0}} HIGH",
        "barAudit.viewAll": "View all {{0}} in Dashboard",

        // FloatingApprovalBanner
        "banner.more": "+{{0}} more",

        // Onboarding - WelcomeStep
        "welcome.tagline": "AI agent safety, in real time",
        "welcome.feature1": "Risk-scores every tool call before it runs",
        "welcome.feature2": "Automatically blocks dangerous operations",
        "welcome.feature3": "Learns from your approve/deny decisions",

        // Onboarding - FeatureTourStep
        "tour.title": "See GuardClaw in Action",
        "tour.subtitle": "Every tool call your AI agent makes — analyzed, scored, and protected.",
        "tour.realtimeTitle": "Real-time Analysis",
        "tour.realtimeDesc": "Every tool call gets a risk score 1–10 before it executes",
        "tour.blockingTitle": "Auto-blocking",
        "tour.blockingDesc": "Dangerous commands are intercepted before they can cause harm",
        "tour.learningTitle": "Learns From You",
        "tour.learningDesc": "Approve once, and GuardClaw remembers — auto-approving next time",
        "tour.youApproved": "You approved: git push",
        "tour.patternSaved": "Pattern saved",
        "tour.autoApproved": "Auto-approved next time",

        // Onboarding - ClaudeCodeStep
        "ccStep.title": "Connect to Claude Code",
        "ccStep.subtitle": "GuardClaw uses Claude Code hooks to intercept tool calls before they run.",
        "ccStep.installed": "Hooks are installed",
        "ccStep.notInstalled": "Hooks not yet installed",
        "ccStep.installHooks": "Install Hooks",
        "ccStep.afterInstall": "After installing, restart Claude Code for the hooks to activate.",
        "ccStep.installSuccess": "Hooks installed — restart Claude Code to activate",

        // Onboarding - ModelSelectionStep
        "modelStep.title": "Choose Your Safety Judge",
        "modelStep.subtitle": "The judge analyzes every tool call and assigns a risk score.\nYou can change this anytime in settings.",
        "modelStep.builtIn": "Built-in",
        "modelStep.builtInDesc": "Runs locally on Apple Silicon via MLX",
        "modelStep.lmStudioDesc": "Requires LM Studio running on port 1234",
        "modelStep.ollamaDesc": "Requires Ollama running on port 11434",
        "modelStep.loadingModels": "Loading models...",
        "modelStep.alreadyDownloaded": "Already downloaded",
        "modelStep.downloadNote": "Download starts in the background once you enter the app. A progress panel will appear.",
        "modelStep.lmStudioInfo": "Make sure LM Studio is running at http://localhost:1234 with a model loaded.",
        "modelStep.ollamaInfo": "Make sure Ollama is running at http://localhost:11434 with a model loaded.",
        "modelStep.startGuardClaw": "Start GuardClaw",

        // Onboarding - ProtectionStep
        "protStep.title": "Choose Protection Level",
        "protStep.subtitle": "You can change this anytime in the Protection settings.",
        "protStep.strict": "Strict",
        "protStep.strictSub": "Active Blocking + Fail-Closed",
        "protStep.strictDesc": "Recommended. Risky calls require approval, and GuardClaw will not silently fail open when the judge is offline.",
        "protStep.balanced": "Balanced",
        "protStep.balancedSub": "Active Blocking + Fail-Open",
        "protStep.balancedDesc": "Keeps approvals on, but if the judge is offline some risky calls may continue without review.",
        "protStep.monitor": "Monitor Only",
        "protStep.monitorSub": "No blocking, log only",
        "protStep.monitorDesc": "Observe without intervening. Safe for evaluating GuardClaw.",
        "protStep.finish": "Finish Setup",

        // Onboarding - SecurityScanStep
        "scanStep.title": "Security Check",
        "scanStep.subtitle": "Deep scan of all agent configs: Claude Code, OpenClaw, Gemini CLI, and Cursor.",
        "scanStep.mcpServers": "MCP Servers",
        "scanStep.skills": "Skills",
        "scanStep.hooks": "Hooks",
        "scanStep.issues": "Issues",
        "scanStep.noIssues": "No security concerns found",
        "scanStep.scanningDesc": "Scanning skills, hooks, MCP servers, and plugin code...",
        "scanStep.runScan": "Run Security Scan",

        // Onboarding - JudgeSetupStep
        "judgeStep.title": "Choose Your Safety Judge",
        "judgeStep.subtitle": "The judge analyzes tool calls and assigns risk scores 1–10.",

        // ModelDownloadProgressPanel
        "download.settingUp": "Setting up {{0}}",
        "download.downloading": "Downloading {{0}}",
        "download.downloaded": "{{0}} downloaded",
        "download.loadingModel": "Loading {{0}}",
        "download.ready": "{{0}} is ready",
        "download.setupFailed": "Setup failed",
        "download.preparing": "Preparing...",
        "download.openJudge": "Open Judge settings to load it into memory",
        "download.progress": "{{0}}% — will finish in the background",
        "download.preparingDownload": "Preparing download...",
        "download.startingScan": "Starting scan...",
    ]

    // MARK: - Chinese Strings

    static let zh: [String: String] = [
        // Common
        "common.install": "安装",
        "common.uninstall": "卸载",
        "common.save": "保存",
        "common.cancel": "取消",
        "common.apply": "应用",
        "common.add": "添加",
        "common.loading": "加载中...",
        "common.connected": "已连接",
        "common.disconnected": "未连接",
        "common.notConnected": "未连接",
        "common.approve": "批准",
        "common.deny": "拒绝",
        "common.review": "审核",
        "common.stop": "停止",
        "common.run": "运行",
        "common.back": "返回",
        "common.skip": "跳过",
        "common.next": "下一步",
        "common.getStarted": "开始使用",
        "common.download": "下载",
        "common.detect": "检测",
        "common.clean": "无风险",
        "common.active": "运行中",
        "common.blocked": "已拦截",
        "common.flagged": "已标记",

        // MenuPopoverView
        "header.title": "GuardClaw",
        "header.daysSuffix": "天",
        "header.saved": "已节省",

        // FooterView
        "footer.openDashboard": "打开仪表盘",
        "footer.checkUpdates": "检查更新",
        "footer.available": "{{0}} 可更新",

        // SettingsView (popover)
        "settings.title": "设置",
        "settings.judge": "安全裁判",
        "settings.builtIn": "内置",
        "settings.lmStudio": "LM Studio",
        "settings.ollama": "Ollama",
        "settings.connections": "连接",
        "settings.protection": "防护",
        "settings.activeBlocking": "主动拦截",
        "settings.blockingOn": "高风险工具调用需要审批",
        "settings.blockingOff": "仅监控 — 不拦截任何操作",
        "settings.failClosed": "离线安全模式",
        "settings.failClosedOn": "当 GuardClaw 或裁判不可达时，高风险工具调用会被拦截，防止未审核通过。",
        "settings.failClosedOff": "风险：如果裁判超时、崩溃或离线，高风险工具调用可能在未经 GuardClaw 审批的情况下继续执行。",
        "settings.gatewayToken": "网关令牌",
        "settings.tokenPlaceholder": "令牌",
        "settings.tokenSaved": "令牌已保存",
        "settings.autoDetected": "已从 OpenClaw 配置自动检测",
        "settings.noTokenFound": "未在 OpenClaw 配置中找到令牌",
        "settings.notFound": "未找到",
        "settings.serverURL": "服务器地址",
        "settings.pollInterval": "轮询间隔：{{0}}秒",
        "settings.hooksInstalled": "钩子已安装 — 请重启 {{0}}",
        "settings.hooksRemoved": "钩子已移除 — 请重启 {{0}}",
        "settings.pluginInstalled": "插件已安装 — 请重启 {{0}}",
        "settings.pluginRemoved": "插件已移除 — 请重启 {{0}}",
        "settings.failed": "失败：{{0}}",
        "settings.rec": "推荐",
        "settings.setupRun": "安装并运行",
        "settings.downloading": "下载中... {{0}}%",
        "settings.loadingModel": "加载模型中...",
        "settings.language": "语言",

        // SidebarView
        "sidebar.monitor": "监控",
        "sidebar.security": "安全",
        "sidebar.tools": "工具",
        "sidebar.settings": "设置",
        "sidebar.dashboard": "仪表盘",
        "sidebar.activity": "活动",
        "sidebar.approvals": "审批",
        "sidebar.rules": "规则",
        "sidebar.memory": "记忆",
        "sidebar.securityScan": "安全扫描",
        "sidebar.benchmark": "基准测试",
        "sidebar.judge": "安全裁判",
        "sidebar.connections": "连接",
        "sidebar.protection": "防护",

        // DashboardView
        "dashboard.title": "仪表盘",
        "dashboard.daysProtected": "保护天数",
        "dashboard.totalEvents": "总事件数",
        "dashboard.pending": "待审批",
        "dashboard.safeEvents": "安全事件",
        "dashboard.warnings": "警告",
        "dashboard.blocked": "已拦截",
        "dashboard.securityScan": "安全扫描",
        "dashboard.risky": "{{0}} 个风险项",
        "dashboard.connections": "连接",
        "dashboard.judgeLabel": "裁判（{{0}}）",
        "dashboard.ready": "就绪",
        "dashboard.tokenUsage": "令牌用量",
        "dashboard.today": "今日",
        "dashboard.cumulative": "累计",
        "dashboard.noTokenData": "暂无令牌数据",
        "dashboard.recentHighRisk": "近期高风险事件",
        "dashboard.inTokens": "输入：{{0}}",
        "dashboard.outTokens": "输出：{{0}}",
        "dashboard.cacheTokens": "缓存：{{0}}",
        "dashboard.requests": "{{0}} 次请求",
        "dashboard.tokens": "{{0}} 令牌",

        // ActivityView
        "activity.title": "活动",
        "activity.backend": "后端",
        "activity.noActivity": "暂无活动",
        "activity.noActivityDesc": "工具调用被拦截时，事件将显示在这里",
        "activity.markAllow": "标记允许",
        "activity.markDeny": "标记拒绝",

        // ApprovalsPageView
        "approvals.title": "审批",
        "approvals.noApprovals": "无待审批项",
        "approvals.noApprovalsDesc": "高风险工具调用将在这里等待审核",
        "approvals.pending": "{{0}} 个待审批",
        "approvals.riskScore": "风险评分",
        "approvals.alwaysApprove": "始终批准",
        "approvals.waiting": "等待 {{0}}秒",
        "approvals.unknownTool": "未知工具",
        "approvals.risk": "风险：{{0}}/10",

        // ProviderCardView
        "card.connection": "连接状态",
        "card.stats": "统计",
        "card.events": "事件：{{0}}",
        "card.safe": "安全",
        "card.warn": "警告",
        "card.block": "拦截",
        "card.judgeTokens": "裁判：{{0}} 令牌 · {{1}} 次调用",
        "card.pendingApprovals": "待审批 ({{0}})",
        "card.recentFlagged": "近期标记/拦截",
        "card.securityScan": "安全扫描",
        "card.scanning": "扫描中...",
        "card.todayTokens": "今日：{{0}}（{{1}} 次请求）",
        "card.totalTokens": "累计：{{0}}（{{1}} 次请求）",
        "card.tools": "工具",
        "card.skills": "技能",
        "card.vulns": "{{0}} 个漏洞",
        "card.riskyCount": "（{{0}} 个风险项）",

        // Detail rows
        "detail.time": "时间",
        "detail.score": "评分",
        "detail.category": "类别",
        "detail.reason": "原因：",
        "detail.judgeBackend": "裁判",

        // RulesView
        "rules.title": "规则",
        "rules.suggestedRules": "推荐规则",
        "rules.basedOnHistory": "基于您的批准/拒绝历史",
        "rules.aiSuggest": "AI 推荐",
        "rules.allow": "允许",
        "rules.block": "拦截",
        "rules.whitelist": "白名单",
        "rules.whitelistDesc": "始终自动放行，不进行评分",
        "rules.blacklist": "黑名单",
        "rules.blacklistDesc": "始终自动拦截",
        "rules.addedTo": "已将 {{0}} 添加到{{1}}",
        "rules.noPatterns": "暂无规则",
        "rules.quickPresets": "快捷预设",
        "rules.presetApplied": "预设已应用",
        "rules.addedWhitelist": "已添加到白名单",
        "rules.addedBlacklist": "已添加到黑名单",
        "rules.patternPlaceholder": "工具名称或匹配模式...",
        "rules.howPatternsWork": "规则匹配说明",
        "rules.patternsHelp": "模式匹配工具名称（如 \"Bash\"）或工具:命令对（如 \"Bash:git status\"）。白名单跳过所有评分；黑名单立即拦截。",
        "rules.allowFileReads": "允许所有文件读取",
        "rules.allowSearches": "允许 Grep/Glob 搜索",
        "rules.allowGit": "允许 git status/log/diff",
        "rules.blockRmRf": "拦截 rm -rf",
        "rules.blockCurlWget": "拦截 curl/wget 上传",
        "rules.blockSSH": "拦截 SSH 密钥访问",
        "rules.blockEnv": "拦截 .env 文件读取",
        "rules.noAISuggestions": "无 AI 建议 — 请确保已加载裁判模型",
        "rules.aiSuggestionFailed": "AI 建议失败：{{0}}",

        // MemoryView
        "memory.title": "记忆",
        "memory.totalDecisions": "总决策数",
        "memory.learnedPatterns": "学习到的模式",
        "memory.autoApprove": "自动批准",
        "memory.confidence": "置信度",
        "memory.toolName": "工具名称",
        "memory.sort": "排序",
        "memory.noPatterns": "暂无模式",
        "memory.noPatternsDesc": "GuardClaw 会从您的批准/拒绝决策中学习",
        "memory.resetAll": "重置所有记忆",
        "memory.resetConfirm": "确定要重置所有学习模式吗？",
        "memory.resetWarning": "此操作不可撤销。所有批准/拒绝模式将被清除。",
        "memory.resetButton": "重置记忆",
        "memory.cleared": "记忆已清除",
        "memory.confidencePercent": "{{0}}% 置信度",

        // AuditView
        "audit.title": "安全扫描",
        "audit.headline": "安全审计",
        "audit.description": "基于 agent-audit 的静态分析。扫描 MCP 配置、凭据、代码漏洞和 OWASP Agentic Top 10。",
        "audit.runScan": "运行扫描",
        "audit.scanning": "扫描中...",
        "audit.configChanged": "上次扫描后配置已更改",
        "audit.configChangedDesc": "MCP 插件或设置已被修改，建议重新扫描。",
        "audit.rescan": "重新扫描",
        "audit.noIssues": "未发现问题",
        "audit.noIssuesDesc": "您的配置看起来是安全的",
        "audit.notScanned": "尚未扫描",
        "audit.notScannedDesc": "点击运行扫描来分析您的代理配置",
        "audit.findings": "发现",
        "audit.tools": "工具",
        "audit.skills": "技能",
        "audit.riskyTools": "风险工具",
        "audit.riskySkills": "风险技能",
        "audit.vulnerabilities": "漏洞",
        "audit.riskyNames": "风险项：{{0}}",
        "audit.vulnsFound": "{{0}} — 发现 {{1}} 个漏洞",
        "audit.blockExtension": "拦截扩展",
        "audit.scanFailed": "扫描失败：{{0}}",

        // BenchmarkView
        "benchmark.title": "基准测试",
        "benchmark.headline": "准确性基准测试",
        "benchmark.description": "使用 30 个精选场景测试安全裁判。分数越高越好 — 目标 85%+。",
        "benchmark.backend": "后端",
        "benchmark.currentJudge": "当前裁判",
        "benchmark.model": "模型",
        "benchmark.auto": "自动",
        "benchmark.abort": "中止",
        "benchmark.runBenchmark": "运行测试",
        "benchmark.latest": "最新：",
        "benchmark.running": "运行中...",
        "benchmark.noResults": "暂无结果",
        "benchmark.noResultsDesc": "运行基准测试来评估裁判准确性",
        "benchmark.resultsHistory": "历史结果",
        "benchmark.unknownModel": "未知模型",
        "benchmark.done": "完成 — 准确率：{{0}}%",
        "benchmark.aborted": "已中止",
        "benchmark.error": "错误：{{0}}",
        "benchmark.correct": "{{0}}/{{1}} 正确{{2}}",
        "benchmark.avgLatency": "平均 {{0}}ms",
        "benchmark.benchmarkAborted": "基准测试已中止",

        // JudgeSettingsView
        "judge.title": "安全裁判",
        "judge.online": "裁判在线",
        "judge.offline": "裁判离线",
        "judge.backend": "后端",
        "judge.model": "模型",
        "judge.none": "无",
        "judge.switchBackend": "切换后端",
        "judge.builtInMLX": "内置 (MLX)",
        "judge.anthropicClaude": "Anthropic Claude",
        "judge.builtInModels": "内置模型",
        "judge.noModels": "无可用内置模型",
        "judge.lmStudioAt": "LM Studio (http://localhost:1234)",
        "judge.ollamaAt": "Ollama (http://localhost:11434)",
        "judge.anthropicKey": "使用环境变量中的 ANTHROPIC_API_KEY",
        "judge.fetchingModels": "获取模型中...",
        "judge.availableModels": "可用模型",
        "judge.fetchModels": "获取模型",
        "judge.testConnection": "测试连接",
        "judge.testConnected": "已连接",
        "judge.testFailed": "连接失败",
        "judge.recommended": "推荐",

        // ConnectionsView
        "connections.title": "连接",
        "connections.hooksInstalled": "钩子已安装",
        "connections.ccDesc": "GuardClaw 通过安装在 ~/.claude/settings.json 中的钩子拦截 Claude Code 工具调用。",
        "connections.hooksActive": "钩子已激活。",
        "connections.installHooks": "安装钩子",
        "connections.ocGateway": "OpenClaw 网关",
        "connections.pluginInstalled": "拦截器插件已安装。",
        "connections.ocNeedPlugin": "需要在 OpenClaw 中安装 GuardClaw 拦截器插件才能启用工具调用拦截。",
        "connections.installPlugin": "安装插件",
        "connections.tokenDesc": "用于实时事件流的网关令牌。",
        "connections.tokenPlaceholder": "网关令牌...",
        "connections.tokenSaved": "令牌已保存，正在重新连接...",
        "connections.geminiDesc": "GuardClaw 通过安装在 ~/.gemini/settings.json 中的钩子拦截 Gemini CLI 工具调用。",
        "connections.cursorDesc": "GuardClaw 通过安装在 ~/.cursor/hooks.json 中的钩子拦截 Cursor 工具调用。",
        "connections.opencodeDesc": "GuardClaw 通过安装在 ~/.config/opencode/plugins/ 中的插件拦截 OpenCode 工具调用。",
        "connections.pluginActive": "插件已激活。",
        "connections.hooksInstalledRestart": "钩子已安装 — 请重启 {{0}} 以激活",
        "connections.pluginInstalledRestart": "插件已安装 — 请重启 {{0}} 以激活",
        "connections.hooksRemovedRestart": "钩子已移除 — 请重启 {{0}}",
        "connections.pluginRemovedRestart": "插件已移除 — 请重启 {{0}}",
        "connections.noTokenFound": "未找到令牌",
        "connections.autoDetected": "已从 OpenClaw 配置自动检测",

        // ProtectionView
        "protection.title": "防护",
        "protection.activeBlocking": "主动拦截",
        "protection.blockingOnDesc": "高风险工具调用需要审批后才能执行。",
        "protection.blockingOffDesc": "仅监控 — GuardClaw 只观察不拦截。",
        "protection.failClosedOffline": "离线安全模式",
        "protection.failClosedOnDesc": "当裁判不可达时，高风险工具调用将被拦截直到防护恢复。",
        "protection.failClosedOffDesc": "当裁判不可达时，高风险工具调用可能在未经 GuardClaw 审核的情况下继续执行。",
        "protection.offlineJudgeBehavior": "离线裁判行为",
        "protection.failOpenRemoved": "已消除失败开放风险",
        "protection.failOpenActive": "失败开放风险存在",
        "protection.failClosedDetail": "如果 GuardClaw 或本地裁判超时、崩溃或离线，高风险操作将停止并等待恢复，而不是在未审核的情况下运行。",
        "protection.failOpenDetail": "如果 GuardClaw 或本地裁判超时、崩溃或离线，高风险操作可能在未审核的情况下继续执行。这优先考虑可用性而非安全性。",
        "protection.strict": "严格",
        "protection.strictDesc": "主动拦截 + 离线安全。最大化防护。",
        "protection.balanced": "平衡",
        "protection.balancedDesc": "主动拦截 + 失败开放。兼顾防护与可用性。",
        "protection.monitorOnly": "仅监控",
        "protection.monitorOnlyDesc": "不拦截。GuardClaw 仅记录和提醒，不进行干预。",
        "protection.presets": "预设方案",
        "protection.blockingEnabled": "已启用拦截",
        "protection.blockingDisabled": "已禁用拦截",
        "protection.failClosedEnabled": "已启用离线安全模式 — GuardClaw 离线时高风险调用将被拦截",
        "protection.failClosedDisabled": "已禁用离线安全模式 — GuardClaw 或裁判故障时高风险调用可能继续执行",

        // BarAuditSection
        "barAudit.securityAudit": "安全审计",
        "barAudit.crit": "{{0}} 严重",
        "barAudit.high": "{{0}} 高危",
        "barAudit.viewAll": "在仪表盘中查看全部 {{0}} 个",

        // FloatingApprovalBanner
        "banner.more": "+{{0}} 个待审",

        // Onboarding - WelcomeStep
        "welcome.tagline": "AI 智能体安全防护，实时守护",
        "welcome.feature1": "在每个工具调用执行前进行风险评分",
        "welcome.feature2": "自动拦截危险操作",
        "welcome.feature3": "从您的批准/拒绝决策中学习",

        // Onboarding - FeatureTourStep
        "tour.title": "体验 GuardClaw",
        "tour.subtitle": "您的 AI 智能体每次工具调用 — 分析、评分、保护。",
        "tour.realtimeTitle": "实时分析",
        "tour.realtimeDesc": "每个工具调用在执行前获得 1-10 的风险评分",
        "tour.blockingTitle": "自动拦截",
        "tour.blockingDesc": "危险命令在造成损害之前被拦截",
        "tour.learningTitle": "自主学习",
        "tour.learningDesc": "批准一次，GuardClaw 会记住 — 下次自动批准",
        "tour.youApproved": "您批准了：git push",
        "tour.patternSaved": "模式已保存",
        "tour.autoApproved": "下次自动批准",

        // Onboarding - ClaudeCodeStep
        "ccStep.title": "连接 Claude Code",
        "ccStep.subtitle": "GuardClaw 使用 Claude Code 钩子在工具调用执行前进行拦截。",
        "ccStep.installed": "钩子已安装",
        "ccStep.notInstalled": "钩子尚未安装",
        "ccStep.installHooks": "安装钩子",
        "ccStep.afterInstall": "安装后，请重启 Claude Code 以激活钩子。",
        "ccStep.installSuccess": "钩子已安装 — 请重启 Claude Code 以激活",

        // Onboarding - ModelSelectionStep
        "modelStep.title": "选择安全裁判",
        "modelStep.subtitle": "裁判会分析每个工具调用并评估风险分数。\n您可以随时在设置中更改。",
        "modelStep.builtIn": "内置",
        "modelStep.builtInDesc": "通过 MLX 在 Apple Silicon 上本地运行",
        "modelStep.lmStudioDesc": "需要在 1234 端口运行 LM Studio",
        "modelStep.ollamaDesc": "需要在 11434 端口运行 Ollama",
        "modelStep.loadingModels": "加载模型中...",
        "modelStep.alreadyDownloaded": "已下载",
        "modelStep.downloadNote": "进入应用后将在后台开始下载，并显示进度面板。",
        "modelStep.lmStudioInfo": "请确保 LM Studio 正在 http://localhost:1234 上运行并已加载模型。",
        "modelStep.ollamaInfo": "请确保 Ollama 正在 http://localhost:11434 上运行并已加载模型。",
        "modelStep.startGuardClaw": "启动 GuardClaw",

        // Onboarding - ProtectionStep
        "protStep.title": "选择防护级别",
        "protStep.subtitle": "您可以随时在防护设置中更改。",
        "protStep.strict": "严格",
        "protStep.strictSub": "主动拦截 + 离线安全",
        "protStep.strictDesc": "推荐。高风险调用需要审批，裁判离线时不会静默放行。",
        "protStep.balanced": "平衡",
        "protStep.balancedSub": "主动拦截 + 失败开放",
        "protStep.balancedDesc": "保持审批开启，但裁判离线时部分高风险调用可能未经审核继续执行。",
        "protStep.monitor": "仅监控",
        "protStep.monitorSub": "不拦截，仅记录",
        "protStep.monitorDesc": "只观察不干预。适合评估 GuardClaw。",
        "protStep.finish": "完成设置",

        // Onboarding - SecurityScanStep
        "scanStep.title": "安全检查",
        "scanStep.subtitle": "深度扫描所有智能体配置：Claude Code、OpenClaw、Gemini CLI 和 Cursor。",
        "scanStep.mcpServers": "MCP 服务器",
        "scanStep.skills": "技能",
        "scanStep.hooks": "钩子",
        "scanStep.issues": "问题",
        "scanStep.noIssues": "未发现安全问题",
        "scanStep.scanningDesc": "正在扫描技能、钩子、MCP 服务器和插件代码...",
        "scanStep.runScan": "运行安全扫描",

        // Onboarding - JudgeSetupStep
        "judgeStep.title": "选择安全裁判",
        "judgeStep.subtitle": "裁判分析工具调用并评估 1-10 的风险分数。",

        // ModelDownloadProgressPanel
        "download.settingUp": "正在设置 {{0}}",
        "download.downloading": "正在下载 {{0}}",
        "download.downloaded": "{{0}} 下载完成",
        "download.loadingModel": "正在加载 {{0}}",
        "download.ready": "{{0}} 已就绪",
        "download.setupFailed": "设置失败",
        "download.preparing": "准备中...",
        "download.openJudge": "请打开裁判设置将其加载到内存",
        "download.progress": "{{0}}% — 将在后台完成",
        "download.preparingDownload": "准备下载...",
        "download.startingScan": "开始扫描...",
    ]
}
